#!/bin/bash

FILE=$1
MESSAGE=$(cat "$FILE")
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo '[A-Z]+-[A-Za-z0-9]+' | tr "[:lower:]" "[:upper:]")

if [[ $TICKET == "" || "$MESSAGE" == "$TICKET"* ]]; then
  exit 0
fi

echo "$TICKET: $MESSAGE" >"$FILE"
